collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.3833455045241863
  brandStrength: 0.6574468
  lightness: 0.164912415901199
  brandColors:
    - '#004358'
    - '#1F8A70'
    - '#BEDB39'
    - '#FFE11A'
    - '#FD7400'
  rhythmicContrast: 0.5086969113908708
typography_spectrum: 0.7258799746632576
layout_spectrum: 0.09148936
name: SmartTax
